export const labelsEnglish = {
    AUD: "Australian Dollar",
    BGN: "Bulgarian Lev",
    BRL: "Brazilian real",
    CAD: "Canadian dollar",
    CHF: "Swiss franc",
    CLP: "Peso",
    CNY: "Yuan renminbi",
    CZK: "Czech Koruna",
    DKK: "Danish Krone",
    EUR: "Euro",
    GBP: "Pound sterling",
    HKD: "Hong Kong Dollar",
    HRK: "Croatian Kuna",
    HUF: "Hungarian Forint",
    IDR: "Indonesian rupee",
    ILS: "Israel new shekel",
    INR: "Rupee",
    ISK: "Icelandic Krona",
    JPY: "Japanese yen",
    KRW: "South Korean won",
    MXN: "Mexican Peso",
    MYR: "Malaysian ringgit",
    NOK: "Norwegian krone",
    NZD: "New Zealand dollar",
    PHP: "Philippine Peso",
    RON: "Romanian Leu",
    RUB: "Russian ruble",
    SEK: "Swedish Krona",
    SGD: "Singapore dollar",
    THB: "Thailand bat",
    TRY: "Turkish lira",
    UAH: "Ukrainian hryvnia",
    USD: "US dollar",
    XDR: "Special Drawing Rights",
    ZAR: "South Africa rand",
};

export const labelsPolish = {
    AUD: "Dolar australijski",
    BGN: "Lew bułgarski",
    BRL: "Real brazylijski",
    CAD: "Dolar kanadyjski",
    CHF: "Frank szwajcarski",
    CLP: "Peso",
    CNY: "Yuan renminbi",
    CZK: "Korona czeska",
    DKK: "Korona duńska",
    EUR: "Euro",
    GBP: "Funt szterling",
    HKD: "Dolar hongkoński",
    HRK: "Kuna chorwacka",
    HUF: "Forint węgierski",
    IDR: "Rupia Indonezyjska",
    ILS: "Nowy szekel Izraelski",
    INR: "Rupia",
    ISK: "Korona islandzka",
    JPY: "Jen japoński",
    KRW: "Won Południowokoreański",
    MXN: "Peso meksykańskie",
    MYR: "Ringgit malezyjski",
    NOK: "Korona norweska",
    NZD: "Dolar nowozelandzki",
    PHP: "Peso filipińskie",
    RON: "Lej rumuński",
    RUB: "Rubel rosyjski",
    SEK: "Korona szwedzka",
    SGD: "Dolar singapurski",
    THB: "Bat Tajski",
    TRY: "Lira turecka",
    UAH: "Hrywna ukraińska",
    USD: "Dolar amerykański",
    XDR: "SDR (MFW)",
    ZAR: "Rand RPA",
};
